### ISSUE TITLE
Make run does not create the plots directory

### ISSUE THREAD

**Issue by omezaldama** [dkhaz/bingo#2]
Working with gfortran on Linux 22.04 LTS. The `make clean` and `make all` commands seem to work correctly:
![image](https://github.com/dkhaz/bingo/assets/51296091/bda64684-2f57-4a94-a012-4d1b44df10de)
But the `/plots` directory did not get created, and when I run `make run` I get this error message:
![image](https://github.com/dkhaz/bingo/assets/51296091/34b63b97-f618-4c46-8126-1a33246cea2f)

By the way, line 126 in bgrnd.f90 is
`     WRITE(FILE_NUM,*),XX(I+1),E_H`
and I think it should be
`     WRITE(FILE_NUM,*) XX(I+1),E_H`

**Comment by ChatterjeeSoham2002** [comment]
I'm facing the same issue. Can you please tell me how did you sort out the problem?

**Comment by omezaldama** [comment]
@ChatterjeeSoham2002  The script does not create the plots directory, you have to create it by hand, and then run the commands
